In [5]:
import numpy as np

In [7]:
arr='hello'
print(arr)

hello


In [3]:
print(np.__version__)

1.26.4


In [77]:
array=np.array([1,2,3,4,5,6])
print(array)
print(type(array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [30]:
ar=np.array(42)
print(ar)

42


In [13]:
#1D array
arr1=np.array((1,2,3,4,5))
print(arr1)
arr1[3:]
arr1[-3:-2]
arr1[::2]
(arr.dtype)

[1 2 3 4 5]


dtype('int32')

In [187]:
#2D array
arr2=np.array([[1,2,3,11],[23,4,7,93]])
print(arr2)

[[ 1  2  3 11]
 [23  4  7 93]]


In [185]:
arry=np.array([[1,23,3],[2,4,5]])
print(arry)
(arr[0:2,1:4])

[[ 1 23  3]
 [ 2  4  5]]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [32]:
arrd=np.array([[[1,2,3],[4,5,6]],[[3,4,5],[6,7,8]]])
print(arrd)
#arrd[3:]
#arrd[1,0,2]
arrd[:,:,1:2:2]

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [6 7 8]]]


array([[[2],
        [5]],

       [[4],
        [7]]])

In [28]:
arr3=np.array([[[11,22,33],[44,55,66]],[[77,88,99],[78,89,978]],[[12,32,123],[56,76,86]]])
print(arr3)

[[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [ 78  89 978]]

 [[ 12  32 123]
  [ 56  76  86]]]


In [27]:
arr1
print(arr1.ndim)


1


In [28]:
arr
print(arr.ndim)

2


In [33]:
ar
arr3
print(ar.ndim)
print(arr3.ndim)

0
3


In [126]:
ary=np.array([1,2,3,4,5],ndmin=5)
print(ary)
ary.ndim
print(ary.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [36]:
arr
arr[1]

array([2, 4, 5])

In [38]:
arr=np.array([1,2,3,4,5])
(arr[3])

4

In [134]:
arr2=np.array([1,2,3,4,5])
(arr2[1])

2

In [51]:
arrd
arrd[0,1,2]
arrd[1,0,1]



4

In [52]:
arrd
arrd[1,-1]

array([6, 7, 8])

In [53]:
arr2
arr[1:4]

array([2, 3, 4])

In [17]:
a=np.array(['apple','cherry'])
print(a.dtype)

<U6


In [43]:
x=np.array([1,2,3,4],dtype='S')
print(x)
print(x.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [52]:
c=np.array([1,2,3,4,5,6],dtype='i4')
print(c.dtype)

int32


In [7]:
d=np.array(['1','2','a'],dtype='i')
print(d.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [9]:
ar=np.array([1.1,3.4,7.3])
nar=ar.astype('i')
print(nar)
print(nar.dtype)

[1 3 7]
int32


In [68]:
bo=np.array([0,1,2,3,4])
ol=bo.astype(bool)
print(ol)
print(ol.dtype)

[False  True  True  True  True]
bool


In [108]:
array
x=array.copy()
array[1]=17
print(x)

[ 1 17  7  4  5  6]


In [106]:
array
y=array.view()
array[2]=7
print(y)

[ 1 17  7  4  5  6]


In [110]:
array=np.array([1,23,45,6,7])
cv=array.view()
cv[1]=28
print(array)
print(cv)

[ 1 28 45  6  7]
[ 1 28 45  6  7]


In [112]:
array=np.array([1,23,45,6,7])
cv=array.view()
x=array.copy()
print(cv.base)
print(x.base)

[ 1 23 45  6  7]
None


In [124]:
arr2
print(arr2.shape)


(2, 4)


In [140]:
#2D reshape
ar1=np.array([1,2,3,4,5,6,7,8])
newar1=ar1.reshape(4,2)
print(newar1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [181]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new=arr.reshape(2,3,2)
print(new)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [189]:
ar=np.array([1,2,3,4,5,6,7,8])
new=ar.reshape(2,2,-1)
print(new)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [209]:
are=np.array([[1,2,3,4],[5,6,7,8]])
ne=are.reshape(-1)
print(ne)

[1 2 3 4 5 6 7 8]


In [193]:
arre=np.array([1,2,3,4,5,6])
for x in arre:
    print(x)

1
2
3
4
5
6


In [195]:
are
for x in are:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [163]:
#2D iteration
aree=np.array([[1,2,3,4],[5,6,7,8]])
#print(aree)
for x in aree:
    #print(x)
    for y in x:
        print(y)


1
2
3
4
5
6
7
8


In [171]:
#3D iteration
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,22,33]]])
print(a)
for x in a:
    for y in x:
        for z in y:
            print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 22 33]]]
1
2
3
4
5
6
7
8
9
11
22
33


In [73]:
arr3=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
for x in np.nditer(arr3):
    print(x)

1
2
3
3
4
5
5
6
7
7
8
9


In [79]:
arr12=np.array([1,2,3,4])
for x in np.nditer(arr12,flags=['buffered'],op_dtypes=['S']):
    print(x)


b'1'
b'2'
b'3'
b'4'


In [103]:
arrr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arrr[:, ::2]):
    print(x)

1
3
5
7


In [107]:
arr12
for idx,x in np.ndenumerate(arr12):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [117]:
arrr
for idx,x in np.ndenumerate(arrr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [127]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr12=np.concatenate((arr1,arr2))
print(arr12)

[1 2 3 4 5 6 7 8]


In [11]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[7,8,9],[13,56,99]])
ar12=np.concatenate((ar1,ar2), axis=1)
print(ar12)

[[ 1  2  3  7  8  9]
 [ 4  5  6 13 56 99]]


In [19]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
ar=np.stack((arr1,arr2),axis=1)
print(ar)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [89]:
arr1
arr2
#arr=np.hstack((arr1,arr2))
#print(arr)
#ar=np.vstack((arr1,arr2))
#print(ar)
a=np.dstack((arr1,arr2))
print(a)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [159]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
r=np.array([[[10,11,12],[13,14,15]],[[16,17,18],[19,20,21]]])
ry=np.dstack((a,r))
print(ry)

[[[ 1  2  3 10 11 12]
  [ 4  5  6 13 14 15]]

 [[ 7  8  9 16 17 18]
  [10 11 12 19 20 21]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]
[[[ 1  2  3]
  [ 4  5  6]
  [10 11 12]
  [13 14 15]]

 [[ 7  8  9]
  [10 11 12]
  [16 17 18]
  [19 20 21]]]


In [197]:
arr12
new=np.array_split(arr12,4)
new2=np.array_split(arr12,2)
new3=np.array_split(arr12,3)
print(new)
print(new2)
print(new3)
print(new[0])
print(new2[1])
print(new3[2])

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[1 2]
[5 6 7 8]
[7 8]


In [223]:
#2d
arr=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9],[9,10,11],[11,12,13]])
ar22=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
ne=np.array_split(arr,3)
ne22=np.array_split(ar22,3)
print(ne)
print(ne22)

[array([[1, 2, 3],
       [3, 4, 5]]), array([[5, 6, 7],
       [7, 8, 9]]), array([[ 9, 10, 11],
       [11, 12, 13]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [213]:
arr
newar=np.array_split(arr,3,axis=1)
print(newar)

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [ 7,  8,  9],
       [ 9, 10, 11],
       [11, 12, 13]])

In [35]:
ar4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
neww=np.hsplit(ar4,3)
print(neww)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [37]:
#get index where 4
sea=np.array([1,2,3,4,5,4,4])
rch=np.where(sea==4)
print(rch)

(array([3, 5, 6], dtype=int64),)


In [51]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.where(a%2!=0)
print(b)

(array([0, 2, 4, 6], dtype=int64),)


In [53]:
a
c=np.where(a%2==0)
print(c)

(array([1, 3, 5, 7], dtype=int64),)


In [57]:
a
x=np.searchsorted(a,5)
print(x)

4


In [99]:
#search from right x
a=np.array([1,2,3,4,5,6,7])
z=np.searchsorted(a,4, side='right')
print(z)

4


In [101]:
a=np.array([1,3,5,7])
x=np.searchsorted(a,[1,2,3]) #123   011
print(x)

[0 1 1]


In [73]:
x=np.array([3,5,1,7,2,4,9])
print(np.sort(x))

[1 2 3 4 5 7 9]


In [75]:
a=np.array(['apple','cherry','blueberry','mango','banana','orange'])
print(np.sort(a))

['apple' 'banana' 'blueberry' 'cherry' 'mango' 'orange']


In [77]:
x=np.array([True,True,False,False,True])
print(np.sort(x))

[False False  True  True  True]


In [83]:
a=np.array([[4,9,8],[2,1,3]])
print(np.sort(a))

[[4 8 9]
 [1 2 3]]


In [105]:
a=np.array([[[5,8,1],[4,2,0]],[[9,8,3],[11,42,33]]])
print(np.sort(a))

[[[ 1  5  8]
  [ 0  2  4]]

 [[ 3  8  9]
  [11 33 42]]]


In [107]:
a=np.array([42,43,44,45])
x=[True,False,False,True]
ax=a[x]
print(ax)

[42 45]


In [144]:
arr=np.array([41,42,43,44])
new=[]
for i in arr:
     if i > 42:
        new.append(True)
     else:
        new.append(False)
z = arr[new]
print(new)
print(z)

[False, False, True, True]
[43 44]


In [156]:
arr=np.array([1,2,3,4,5,6])
neww=[]
for i in arr:
    if i%2==0:
        neww.append(True)
    else:
        neww.append(False)
y=arr[neww]
print(y)

[2 4 6]


In [8]:
def add(x,y):
    return x+y
add=np.frompyfunc(add,2,1)
print(add([1,2,3,4],[5,6,7,8]))


[6 8 10 12]


In [12]:
print(type(np.add))
print(type(np.concatenate))


<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [22]:
if type(np.add)!=np.ufunc:
    print('add is not ufunc')
else:
    print('add is ufunc')

add is ufunc


In [21]:
x=np.array([5,9,8,4,7])
y=np.array([6,7,8,9,10])
z=np.add(x,y)
print(z)

[11 16 16 13 17]


In [5]:
x=np.array([5,9,8,4,7])
y=np.array([6,7,8,9,10])
z=np.subtract(x,y)
print(z)

[-1  2  0 -5 -3]


In [9]:
x=np.array([6,9,8,8,72])
y=np.array([3,7,8,4,9])
z=np.divide(x,y)
print(z)

[2.         1.28571429 1.         2.         8.        ]


In [27]:
x=np.array([20,9,8,41,13])
y=np.array([3,1,4,2,10])
z=np.power(x,y)
print(z)

[     8000         9      4096      1681 419538377]


In [13]:
x=np.array([5,9,8,4,7])
y=np.array([6,7,8,9,10])
z=np.mod(x,y)
print(z)

[5 2 0 4 7]


In [33]:
x=np.array([13,45,67,69,89,85])
y=np.array([3,4,7,8,2,5])
z=np.divmod(x,y)
print(z)

(array([ 4, 11,  9,  8, 44, 17]), array([1, 1, 4, 5, 1, 0]))


In [19]:
x=np.array([5,9,8,4,7])
y=np.array([6,7,8,8,10])
z=np.multiply(x,y)
print(z)  

[30 63 64 32 70]


In [17]:
x=np.array([-5,9,8,-4,-7])
n=np.absolute(x)
print(n)

[5 9 8 4 7]


In [31]:
a=np.trunc([4.456,-3.14534])
print(a)


[ 4. -3.]


In [33]:
a=np.fix([4.456,-3.14534])
print(a)


[ 4. -3.]


In [39]:
a=np.around(4.631,2)
print(a)

4.63


In [47]:
x=np.floor([-3.4234,3.17678])
print(x)

[-4.  3.]


In [51]:
c=np.ceil([-3.1666,3.54332])
print(c)

[-3.  4.]


In [59]:
 x=np.arange(1,10)
print(np.log2(x))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [61]:
a=np.arange(1,10)
print(np.log10(a))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [63]:
a=np.arange(1,10)
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [65]:
from math import log
import numpy as np
nplog=np.frompyfunc(log,2,1)
print(nplog(100,15))


1.7005483074552052


In [3]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
new=np.add(a,b)
print(new)           

[2 4 6 8]


In [23]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
new=np.sum([a,b])
print(new)    

20


In [15]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
new=np.sum([a,b],axis=1)
print(new)    

[10 10]


In [21]:
#cumulative sum(1,1*2,1*2*3,...)
ar=np.array([1,2,3,4,5])
arr=np.cumsum(ar)
print(arr)

[ 1  3  6 10 15]


In [25]:
#products of elmnts(1*2*3*....)
x=np.array([2,5,7,8,5])
z=np.prod(x)
print(z)

2800


In [29]:
#(x*y continues...)
x=np.array([1,2,3,4,5])
y=np.array([1,2,3,4,5])
z=np.prod([x,y])
print(z)

14400


In [31]:
x=np.array([1,2,3,4,5])
y=np.array([1,2,3,4,5])
z=np.prod([x,y],axis=1)
print(z)

[120 120]


In [33]:
#cummulative
ar=np.array([1,2,3,4,5])
arr=np.cumprod(ar)
print(arr)

[  1   2   6  24 120]


In [35]:
ar=np.array([10,20,30,4,54])
arr=np.diff(ar)
print(arr)

[ 10  10 -26  50]


In [63]:
#(20-10,30-20,....)(10-10,-26-10,....)
ar=np.array([10,15,25,5])
arr=np.diff(ar,n=2)
print(arr)

[  5 -30]


In [41]:
#LCM(comon multiple)
num1=4
num2=6
x=np.lcm(num1,num2)
print(x)


12


In [47]:
a=np.array([3,6,9])
x=np.lcm.reduce(a)
print(x)

18


In [51]:
x=np.arange(1,11)
y=np.lcm.reduce(x)
print(y)

2520


In [53]:
#GCD(common Denominator)
n=6
nu=9
x=np.gcd(n,nu)
print(x)

3


In [57]:
n=np.array([4,20,36,28,40])
x=np.gcd.reduce(n)
print(x)

4


In [65]:
n=np.array([4,20,36,28,40])
x=np.gcd.reduce(n)
print(x)

4


In [13]:
 x=np.sin(np.pi/2)
print(x)

1.0


In [15]:
ar=np.array([np.pi/2,np.pi/3,np.pi/4])
arr=np.sin(ar)
print(arr)

[1.         0.8660254  0.70710678]


In [17]:
a=np.array([90,360,180,270])
x=np.deg2rad(a)
print(x)

[1.57079633 6.28318531 3.14159265 4.71238898]


In [19]:
arr=np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
x=np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [21]:
x=np.arcsin(1.0)
print(x)

1.5707963267948966


In [23]:
x=np.array([1,1.0,-1])
y=np.arcsin(x)
print(y)

[ 1.57079633  1.57079633 -1.57079633]


In [27]:
base=4
perp=4
x=np.hypot(base,perp)
print(x)

5.656854249492381


In [29]:
x=np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [33]:
x=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
y=np.cosh(x)
print(y)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [35]:
x=np.arcsinh(1.0)
print(x)

0.881373587019543


In [37]:
x=np.array([0.1,0.2,0.5])
y=np.arctanh(x)
print(y)

[0.10033535 0.20273255 0.54930614]


In [39]:
x=np.array([1,2,3,4,2,3,3,1,5,7])
y=np.unique(x)
print(y)

[1 2 3 4 5 7]


In [41]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.union1d(x,y)
print(z)

[1 2 3 4 5 6 7 8]


In [47]:
a=np.array([1,2,3,4])
ar=np.array([5,4,1,8])
arr=np.intersect1d(a,ar)#,assume_unique=True)
print(arr)

[1 4]


In [49]:
a=np.array([1,2,3,4])
ar=np.array([5,4,1,8])
arr=np.setdiff1d(a,ar)
print(arr)

[2 3]


In [ ]:
a=np.array([1,2,3,4])
ar=np.array([5,4,1,8])
arr=np.setxor1d(a,ar)
print(arr)